M48
; DRILL file KiCad 10.0.1 date 2026-07-02T23:40:45
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-02T23:40:45+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X40.005Y-24.51
X40.005Y-30.29
T2
X44.1Y-72.2
X50.1Y-66.2
M30
